# Generated by Django 3.2.7 on 2023-10-13 10:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='school',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='parent',
            name='create_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email_address',
            field=models.EmailField(default='null@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='create_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='create_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email_address',
            field=models.EmailField(default='null@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.school'),
        ),
    ]
