# Generated by Django 3.2.7 on 2023-09-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='confirm_password',
        ),
    ]
