# Generated by Django 3.2.7 on 2023-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_school_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='confirm_password',
            field=models.CharField(default='well', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='create_password',
            field=models.CharField(default='wealth', max_length=200),
            preserve_default=False,
        ),
    ]
