# Generated by Django 3.2.7 on 2023-09-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_phone_number',
        ),
    ]
