# Generated by Django 3.2.7 on 2023-09-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_remove_grade_subjects'),
        ('students', '0002_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade.grade'),
        ),
    ]
