# Generated by Django 4.2.5 on 2023-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date_added',
            new_name='date_added_at',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='date_updated',
            new_name='date_updated_at',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='homework',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='competency',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.CharField(default=1, max_length=54),
            preserve_default=False,
        ),
    ]
