# Generated by Django 4.2.5 on 2023-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_rename_date_added_assignment_date_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.CharField(max_length=54, null=True),
        ),
    ]
