# Generated by Django 4.2.5 on 2023-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_category_alter_assignment_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='competency',
        ),
        migrations.AddField(
            model_name='assignment',
            name='materials',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
