# Generated by Django 4.2.5 on 2023-09-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
    ]
