# Generated by Django 4.2.5 on 2023-09-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_alter_assignment_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='competency',
            field=models.CharField(max_length=100),
        ),
    ]
