# Generated by Django 4.2.5 on 2023-09-14 15:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_alter_shop_category'),
        ('assignment', '0008_alter_assignment_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
