# Generated by Django 4.2.5 on 2023-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_added_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
