# Generated by Django 4.2.5 on 2023-09-15 12:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields
import multiselectfield.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subjects', models.CharField(default='', max_length=50)),
                ('grades', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6')], max_length=11, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(6)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('school_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('date_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
    ]
