# Generated by Django 3.2.7 on 2023-09-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='subjects',
        ),
    ]
