# Generated by Django 3.2.7 on 2023-09-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subjects',
        ),
    ]
