# Generated by Django 4.2.5 on 2023-09-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subjects',
            field=models.CharField(),
        ),
    ]
