# Generated by Django 3.2.12 on 2023-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_school_date_added_remove_school_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='school',
            name='date_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
    ]
