# Generated by Django 3.2.7 on 2023-09-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('comments', '0003_auto_20230918_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parent'),
        ),
    ]
