# Generated by Django 3.2.7 on 2023-09-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('comments', '0005_alter_comment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
    ]
