# Generated by Django 3.2.7 on 2023-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_is_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(),
        ),
    ]
