# Generated by Django 3.2.7 on 2023-09-27 08:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('password', models.CharField(max_length=255)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('date_added_at', models.DateTimeField(auto_now_add=True, verbose_name='Date_Added')),
                ('date_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date_Updated')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
