# Generated by Django 3.2.7 on 2023-09-29 08:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='null', max_length=128, region='KE'),
            preserve_default=False,
        ),
    ]
