# Generated by Django 4.2.5 on 2023-09-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_parent_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
    ]
