# Generated by Django 4.2.5 on 2023-09-11 06:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_remove_parent_password_remove_parent_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='date_added',
            new_name='date_added_at',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='date_updated',
            new_name='date_updated_at',
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='KE', unique=True),
        ),
    ]
