# Generated by Django 4.2.5 on 2023-09-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_rename_date_added_parent_date_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone_number',
        ),
    ]
