# Generated by Django 4.2.3 on 2023-09-14 13:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_parent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True),
        ),
    ]
