# Generated by Django 4.2.5 on 2023-09-13 13:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
