# Generated by Django 4.2.5 on 2023-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_alter_assignment_category'),
        ('shop', '0004_category_alter_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
