# Generated by Django 4.2.5 on 2023-09-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_user_comment_commentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['updated_at']},
        ),
    ]
