# Generated by Django 4.2.5 on 2023-09-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_remove_parent_password_remove_parent_students'),
        ('students', '0002_remove_student_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.parent'),
        ),
    ]
