# Generated by Django 4.2.5 on 2023-09-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_date_added_student_date_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_phone_number',
        ),
    ]
