# Generated by Django 4.2.5 on 2023-09-11 14:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='KE', unique=True),
        ),
    ]
