# Generated by Django 4.2.3 on 2023-09-14 13:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE'),
        ),
    ]
