# Generated by Django 4.2.5 on 2023-09-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[(1, 'English'), (2, 'Kiswahili'), (3, 'Mathematics'), (4, 'Integrated Science'), (5, 'Social Studies'), (6, 'Business Studies'), (7, 'Agriculture'), (8, 'Pre-technical and Pre-Career Studies'), (9, 'Religious Studies Education')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
