# Generated by Django 4.2.5 on 2023-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Mathematics', 'Mathematics'), ('Integrated Science', 'Integrated Science'), ('Social Studies', 'Social Studies'), ('6', 'Business Studies'), ('7', 'Agriculture'), ('8', 'Pre-technical and Pre-Career Studies'), ('9', 'Religious Studies Education')], max_length=100),
        ),
    ]
