# Generated by Django 3.2.7 on 2023-09-18 05:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_alter_subject_subject_name'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=54, null=True)),
                ('competency', models.CharField(max_length=100)),
                ('task', models.TextField()),
                ('materials', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_added_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
