# Generated by Django 3.2.7 on 2023-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_task1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='task1',
        ),
    ]
